// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZK2TI-5O8NqnG0DtHCqG7TK5PPVTA3kc',
    appId: '1:765609639869:web:550fb103ac7cd36aef9cd4',
    messagingSenderId: '765609639869',
    projectId: 'instaclone-eagas',
    authDomain: 'instaclone-eagas.firebaseapp.com',
    storageBucket: 'instaclone-eagas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFKw_FLPxdFrR9iS7dapqLIlC7RUaQfY',
    appId: '1:765609639869:android:ec237cc7095dbe49ef9cd4',
    messagingSenderId: '765609639869',
    projectId: 'instaclone-eagas',
    storageBucket: 'instaclone-eagas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFbKZ-TiZJr7XsGDDpBJ_h7q5QKsEz-I',
    appId: '1:765609639869:ios:3757cd9c4fb69c06ef9cd4',
    messagingSenderId: '765609639869',
    projectId: 'instaclone-eagas',
    storageBucket: 'instaclone-eagas.appspot.com',
    iosClientId: '765609639869-6uqgo8qvn7vqlvtd76p29p2onjiq3sbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJFbKZ-TiZJr7XsGDDpBJ_h7q5QKsEz-I',
    appId: '1:765609639869:ios:041cb7c9b3293e8eef9cd4',
    messagingSenderId: '765609639869',
    projectId: 'instaclone-eagas',
    storageBucket: 'instaclone-eagas.appspot.com',
    iosClientId: '765609639869-tmphjcpd192srum94l210mair9eppq65.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
